### ISSUE TITLE
Limited subscription data

### ISSUE THREAD

**Issue by steveputman** [fjgalesloot/roon-extension-mqtt#12]
Thanks for this very handy extension--very cool!

When I monitor all messages being passed through the broker (with two zones playing in this example, but same result with one zone), I only see `roon/[zonename]/queue_time_remaining` and `roon/[zonename]/seek_position`. You refer to the `now_playing` and other topics, so I wasn't sure if I was missing something here.

Thanks again!

**Comment by CaseyRo** [comment]
what's the question exactly? I'm actually getting all data back, just takes some time to populate (only sends data to the broker on change, doesn't use ```retain``` for instance to send an initial value)

**Comment by steveputman** [comment]
@CaseyRo Just saw your response--thanks! LIke you suspected, I was expecting an initial value.
