### ISSUE TITLE
any build for arm/raspberry platform

### ISSUE THREAD

**Issue by nidr** [fjgalesloot/roon-extension-mqtt#14]
Dear all,

i strugle to get this docker running on my raspberry pi 4, which I use for home automation extensions.

If I specify platfor command with linux/arm/v7 I get following issue:
```
root@loxberry:/opt/roonmqtt# docker run -v /opt/roonmqtt/:/usr/src/app/config/ --platform linux/arm/v7 fjgalesloot/roon-extension-mqtt
Unable to find image 'fjgalesloot/roon-extension-mqtt:latest' locally
latest: Pulling from fjgalesloot/roon-extension-mqtt
Digest: sha256:4e06957c9fd550cc4ed66dcce7328d52f6b8a14572710f9a8cac7af78a10bf13
Status: Image is up to date for fjgalesloot/roon-extension-mqtt:latest
docker: Error response from daemon: image with reference fjgalesloot/roon-extension-mqtt was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64.
See 'docker run --help'.
```
Is there any way to get this running on raspberry?
Thank you so much for your work!
Rest regargs, NiDr

**Comment by volschin** [comment]
You could build it yourself on RPi with the Dockerfile.

**Comment by nidr** [comment]
Thank you, but unfortunatly i did not succeed. Maybe I did something wrong?
Just to be sure: on the one hand I have the roon extensionmanager docker up and running on my raspberry docker host and in addition to that I do need another docker with a selfbuild image from dockerfile?

Please see atatched the log of the unsucessful build with portainer and dockerfile. 

Last lines are 
Step 6/10 : COPY package*.json /usr/src/app/
COPY failed: no source files were specified

[docker-build.txt](https://github.com/fjgalesloot/roon-extension-mqtt/files/6845991/docker-build.txt)

If i try to install it within roon extension manager i also do get the error in the logfile, that arm is not supported.

Thank you very much!

**Comment by fjgalesloot** [comment]
There are ARM images available on Docker Hub that can be loaded with the roon extension manager. So you should be able to use those out of the box.
