### ISSUE TITLE
Group Zones

### ISSUE THREAD

**Issue by JamesKennewell** [fjgalesloot/roon-extension-mqtt#3]
Is it possible to group zones together using mqtt? if not is this something that could be implented?

**Comment by fjgalesloot** [comment]
If the Roon API supports this, it could me implemented. What is your use case?

**Comment by fjgalesloot** [comment]
Hi, @JamesKennewell. I think this is possible using Roon API. Do you still have a use case for this? Then I could look into it.

**Comment by volschin** [comment]
I often hear in the Living room, but want to extend to my kitchen zone if there is motion. This needs the control to group both zones. Command to group will be sent if motion is detected and ungroup after some time no motion is there.

**Comment by fjgalesloot** [comment]
Cool use case! I'm working on a non-related project right now, but I'll see what I can do ;-).

**Comment by fjgalesloot** [comment]
In the latest beta version 2.2.0b I added this functionality.
